# Generated by Django 6.0.2 on 2026-02-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
