# Generated by Django 6.0.2 on 2026-02-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iinstitutes_list', '0002_institute_admin_key'),
        ('professors', '0005_professorexperience_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorsPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default='')),
                ('payment_amount', models.IntegerField(default=0)),
                ('payment_status', models.CharField(default='', max_length=20)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professors_payments', to='iinstitutes_list.institute')),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='professors.professor')),
            ],
        ),
    ]
