# Generated by Django 6.0.2 on 2026-02-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('professors', '0005_professorexperience_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorspayments',
            name='month_year',
            field=models.CharField(default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='professorspayments',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='professorspayments',
            unique_together={('professor', 'month_year')},
        ),
    ]
