# Generated by Django 6.0.2 on 2026-03-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0005_remove_schedules_and_unique_ids_artifacts'),
        ('payments', '0002_professorspayments_month_year_and_more'),
        ('professors', '0007_professor_prof_inst_email_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='professorspayments',
            index=models.Index(fields=['institute', 'month_year'], name='pay_inst_month_idx'),
        ),
        migrations.AddIndex(
            model_name='professorspayments',
            index=models.Index(fields=['institute', 'professor'], name='pay_inst_prof_idx'),
        ),
    ]
