# Generated by Django 6.0.2 on 2026-03-30 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iinstitutes_list', '0007_rename_name_add_super_admin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('professor', 'Professor')], max_length=20)),
                ('source_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('archived_data', models.JSONField(default=dict)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='iinstitutes_list.institute')),
            ],
            options={
                'ordering': ['-archived_at', '-id'],
                'indexes': [
                    models.Index(fields=['institute', 'entity_type'], name='archive_inst_entity_idx'),
                    models.Index(fields=['institute', 'source_id'], name='archive_inst_source_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('institute', 'entity_type', 'source_id'), name='uniq_archive_institute_entity_source'),
                ],
            },
        ),
    ]
