# Generated by Django 6.0.2 on 2026-04-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiverecord',
            options={},
        ),
    ]
