# Generated by Django 6.0.2 on 2026-03-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0002_institute_admin_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='institute',
            name='status_expires_at',
            field=models.DateTimeField(blank=True, help_text='When set, institute automatically stops after this time', null=True),
        ),
    ]
