# Generated by Django 6.0.2 on 2026-03-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0003_institute_status_institute_status_expires_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='status',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='status_expires_at',
        ),
        migrations.AddField(
            model_name='institute',
            name='event_status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='active', help_text="Controls whether this institute's events are accessible", max_length=10),
        ),
        migrations.AddField(
            model_name='institute',
            name='event_timer_end',
            field=models.DateTimeField(blank=True, help_text='When set, events auto-stop after this date/time', null=True),
        ),
    ]
