# Generated by Django 6.0.2 on 2026-03-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0005_remove_schedules_and_unique_ids_artifacts'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['name'], name='institute_name_idx'),
        ),
    ]
