# Generated by Django 6.0.2 on 2026-03-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0007_rename_name_add_super_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='academic_terms_type',
            field=models.CharField(choices=[('semester', 'Semester Wise'), ('year', 'Year Wise')], default='semester', help_text='Choose whether this institute uses semester-wise or year-wise academic terms.', max_length=20),
        ),
    ]
