# Generated by Django 6.0.2 on 2026-04-13 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_activities', '0003_academicterm'),
        ('iinstitutes_list', '0008_institute_academic_terms_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='academic_terms_type',
        ),
    ]
