# Generated by Django 6.0.2 on 2026-03-19 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iinstitutes_list', '0005_remove_schedules_and_unique_ids_artifacts'),
        ('professors', '0007_professor_prof_inst_email_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_attendance_records', to='iinstitutes_list.institute')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_attendance_records', to='professors.professor')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['institute', 'date'], name='prof_att_app_inst_date_idx'),
                    models.Index(fields=['professor', 'date'], name='prof_att_app_prof_date_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('professor', 'date'), name='uniq_prof_attendance_per_day'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ProfessorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('reject', 'Reject')], default='approved', max_length=10)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_leave_records', to='iinstitutes_list.institute')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_leave_records', to='professors.professor')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['institute', 'date'], name='prof_leave_app_inst_date_idx'),
                    models.Index(fields=['institute', 'status'], name='prof_leave_app_inst_status_idx'),
                    models.Index(fields=['professor', 'date'], name='prof_leave_app_prof_date_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('professor', 'date'), name='uniq_prof_leave_per_day'),
                ],
            },
        ),
    ]
