# Generated by Django 6.0.2 on 2026-02-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(default='', max_length=10)),
                ('course', models.CharField(default='', max_length=100)),
                ('address', models.TextField(default='')),
                ('mobile', models.CharField(default='', max_length=15)),
                ('father_name', models.CharField(default='', max_length=100)),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('parent_contact', models.CharField(default='', max_length=15)),
                ('qualification', models.CharField(default='', max_length=100)),
                ('passing_year', models.IntegerField(default=0)),
            ],
        ),
    ]
