# Generated by Django 6.0.2 on 2026-02-16 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='parent_contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
        migrations.AddField(
            model_name='student',
            name='identity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='StudentCOntactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('parmannent_address', models.TextField(default='')),
                ('current_address', models.TextField(default='')),
                ('mobile', models.CharField(default='', max_length=15)),
                ('father_name', models.CharField(default='', max_length=100)),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('parent_contact', models.CharField(default='', max_length=15)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_details', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentEducationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(default='', max_length=100)),
                ('passing_year', models.IntegerField(default=0)),
                ('instutute_name', models.CharField(default='', max_length=100)),
                ('marks_obtained', models.CharField(default='', max_length=10)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='students.student')),
            ],
        ),
    ]
