# Generated by Django 6.0.2 on 2026-02-19 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_address_remove_student_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAdmissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enrollment_number', models.CharField(default='', max_length=50)),
                ('roll_number', models.CharField(default='', max_length=50)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.CharField(default='', max_length=20)),
                ('student_status', models.CharField(default='', max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admission_details', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=20)),
                ('batch', models.CharField(default='', max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=100)),
                ('branch', models.CharField(default='', max_length=100)),
                ('session_mode', models.CharField(default='', max_length=50)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='course_details', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_fee_amount', models.FloatField(default=0.0)),
                ('paid_amount', models.FloatField(default=0.0)),
                ('pending_amount', models.FloatField(default=0.0)),
                ('othoer_amount', models.FloatField(default=0.0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee_details', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSystemDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_personal_id', models.CharField(default='', max_length=50)),
                ('library_card_number', models.CharField(default='', max_length=50)),
                ('hostel_details', models.CharField(default='', max_length=100)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_details', to='students.student')),
            ],
        ),
    ]
