# Generated by Django 6.0.2 on 2026-02-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentadmissiondetails_studentcourseassignment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentadmissiondetails',
            old_name='Enrollment_number',
            new_name='enrollment_number',
        ),
    ]
