# Generated by Django 6.0.2 on 2026-02-19 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_enrollment_number_studentadmissiondetails_enrollment_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfeedetails',
            old_name='othoer_amount',
            new_name='other_amount',
        ),
    ]
