# Generated by Django 6.0.2 on 2026-02-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentadmissiondetails',
            name='student_status',
        ),
        migrations.RemoveField(
            model_name='studentfeedetails',
            name='other_amount',
        ),
    ]
