# Generated by Django 6.0.2 on 2026-02-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_studentadmissiondetails_student_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
