# Generated by Django 6.0.2 on 2026-02-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsystemdetails',
            name='varification_status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
