# Generated by Django 6.0.2 on 2026-03-03 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentsystemdetails_varification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_leave', models.BooleanField(default=False)),
                ('branch', models.CharField(default='', max_length=20)),
                ('class_name', models.CharField(default='', max_length=20)),
                ('year_semester', models.CharField(default='', max_length=20)),
                ('is_present', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
