# Generated by Django 6.0.2 on 2026-03-03 08:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.CreateModel(
            name='AttedanceDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='attedance_date',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.attedancedate'),
            preserve_default=False,
        ),
    ]
