# Generated by Django 6.0.2 on 2026-03-03 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_attendance_attedance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attedancedate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_dates', to='students.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attedance_date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.attedancedate'),
        ),
    ]
