# Generated by Django 6.0.2 on 2026-03-04 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_alter_attedancedate_student_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
