# Generated by Django 6.0.2 on 2026-03-04 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectsAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=30)),
                ('unit', models.CharField(default='', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects_assigned', to='students.student')),
            ],
        ),
    ]
