# Generated by Django 6.0.2 on 2026-03-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_sync_student_schema_with_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subjectsassigned',
            index=models.Index(fields=['student', 'subject'], name='subj_assigned_student_subj_idx'),
        ),
    ]
