# Generated by Django 6.0.2 on 2026-03-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0006_institute_institute_name_idx'),
        ('students', '0017_add_subjects_assigned_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institute'], name='student_institute_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institute', 'name'], name='student_inst_name_idx'),
        ),
        migrations.AddIndex(
            model_name='studentadmissiondetails',
            index=models.Index(fields=['enrollment_number'], name='admission_enrollment_idx'),
        ),
        migrations.AddIndex(
            model_name='studentadmissiondetails',
            index=models.Index(fields=['roll_number'], name='admission_roll_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcontactdetails',
            index=models.Index(fields=['email'], name='contact_email_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcontactdetails',
            index=models.Index(fields=['mobile'], name='contact_mobile_idx'),
        ),
        migrations.AddIndex(
            model_name='studentcourseassignment',
            index=models.Index(fields=['class_name', 'branch', 'academic_term'], name='course_assign_class_idx'),
        ),
        migrations.AddIndex(
            model_name='studentsystemdetails',
            index=models.Index(fields=['student_personal_id'], name='system_personal_id_idx'),
        ),
    ]
