# Generated by Django 6.0.2 on 2026-04-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_studentadmissiondetails_start_class_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentadmissiondetails',
            name='academic_year',
            field=models.CharField(default='', max_length=40),
        ),
    ]
