# Generated by Django 6.0.2 on 2026-04-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_alter_studentadmissiondetails_academic_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AttedanceDate',
            new_name='AttendanceDate',
        ),
        migrations.AlterField(
            model_name='studentcontactdetails',
            name='parmannent_address',
            field=models.TextField(db_column='parmannent_address', default=''),
        ),
        migrations.RenameField(
            model_name='studentcontactdetails',
            old_name='parmannent_address',
            new_name='permanent_address',
        ),
        migrations.AlterField(
            model_name='studenteducationdetails',
            name='instutute_name',
            field=models.CharField(db_column='instutute_name', default='', max_length=100),
        ),
        migrations.RenameField(
            model_name='studenteducationdetails',
            old_name='instutute_name',
            new_name='institute_name',
        ),
        migrations.AlterField(
            model_name='studentsystemdetails',
            name='varification_status',
            field=models.CharField(db_column='varification_status', default='', max_length=20),
        ),
        migrations.RenameField(
            model_name='studentsystemdetails',
            old_name='varification_status',
            new_name='verification_status',
        ),
        migrations.AlterField(
            model_name='studentfeedetails',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentfeedetails',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentfeedetails',
            name='total_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
