# Generated by Django 6.0.2 on 2026-03-23 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iinstitutes_list', '0005_remove_schedules_and_unique_ids_artifacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_professor_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('email', models.EmailField(db_index=True, default='', max_length=254)),
                ('professor_personal_id', models.CharField(db_index=True, default='', max_length=30)),
                ('professor_data', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_professors', to='iinstitutes_list.institute')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['institute', 'source_professor_id'], name='pub_prof_lookup_idx'),
                    models.Index(fields=['institute', 'name'], name='pub_prof_name_idx'),
                    models.Index(fields=['institute', 'email'], name='pub_prof_email_idx'),
                    models.Index(fields=['institute', 'professor_personal_id'], name='pub_prof_pid_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('institute', 'source_professor_id'), name='uniq_published_professor_institute_source'),
                ],
            },
        ),
    ]
