"""
Django settings for institute_api project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
from dotenv import load_dotenv
from urllib.parse import urlparse, parse_qsl

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_u%h!_q2l_l42cg#q@h3ocx=!r3=#v!icu*arh4na-zxls9sdq'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

ALLOWED_HOSTS = ['*','localhost', '127.0.0.1', '.amazonaws.com','main.d3e0ptm41k0biu.amplifyapp.com']
APPEND_SLASH = False

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework',
    'corsheaders',
    'students',
    'my_auth',
    'iinstitutes_list',
    'syllabus',
    'professors',
    'payments',
    'attendance',
    'notifications',
    'set_exam_data',
    'weekly_exam_schedule',
    'published_student',
    'published_exam_result',
    'professor_attendance',
    'super_admin_account_details',
    'employee_account_details',
    'payment_notification',
    'published_professors',
    'professor_leaves',
    'published_schedules',
    'subordinate_access',
    'archives',
    'activity_feed',
    'default_activities',
    'contact_us',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'institute_api.urls'
CORS_ALLOW_ALL_ORIGINS = True 

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://main.d3e0ptm41k0biu.amplifyapp.com",
    "https://educonnectz.in",
    "https://www.educonnectz.in",
]

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-admin-key",
    "x-personal-key",
]


AUTHENTICATION_BACKENDS = [
    'my_auth.backends.EmailBackend',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'institute_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
#  }

tmpPostgres=urlparse('postgresql://neondb_owner:npg_FJ6GVXOpv1um@ep-proud-mud-ai9wuq5b-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require')
#tmpPostgres = urlparse(os.getenv("DATABASE_URL"))
DATABASES = {
   'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.path.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
        "CONN_MAX_AGE": 600,
        "CONN_HEALTH_CHECKS": True,
        "OPTIONS": {
            "sslmode": "require",
            "connect_timeout": 3,
        },
    }
}



# DATABASES = {
#     'default': dj_database_url.parse(
#         "postgresql://neondb_owner:npg_FJ6GVXOpv1um@ep-proud-mud-ai9wuq5b-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
#     )
# }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Custom User Model
AUTH_USER_MODEL = 'my_auth.User'

# ── Email (SMTP) ──────────────────────────────────────────────
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('EMAIL_HOST_USER', '')
CONTACT_US_EMAIL_HOST = os.getenv('CONTACT_US_EMAIL_HOST', EMAIL_HOST)
CONTACT_US_EMAIL_PORT = int(os.getenv('CONTACT_US_EMAIL_PORT', EMAIL_PORT))
CONTACT_US_EMAIL_USE_TLS = os.getenv('CONTACT_US_EMAIL_USE_TLS', str(EMAIL_USE_TLS)) == 'True'
CONTACT_US_EMAIL_HOST_USER = os.getenv('CONTACT_US_EMAIL_HOST_USER', EMAIL_HOST_USER)
CONTACT_US_EMAIL_HOST_PASSWORD = os.getenv('CONTACT_US_EMAIL_HOST_PASSWORD', EMAIL_HOST_PASSWORD)
CONTACT_US_FROM_EMAIL = os.getenv('CONTACT_US_FROM_EMAIL', CONTACT_US_EMAIL_HOST_USER)
CONTACT_US_RECIPIENT_EMAIL = os.getenv('CONTACT_US_RECIPIENT_EMAIL', CONTACT_US_EMAIL_HOST_USER)
CONTACT_US_FROM_NAME = os.getenv('CONTACT_US_FROM_NAME', 'educonnectz')
CONTACT_US_SUBJECT = os.getenv('CONTACT_US_SUBJECT', 'Admin Access Contact Request')

# ── Twilio (SMS) ──────────────────────────────────────────────
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN  = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.getenv('TWILIO_FROM_NUMBER', '')

# ── Admin API Key ─────────────────────────────────────────────
ADMIN_KEY = os.getenv('ADMIN_KEY', '')

# ── Data Encryption ───────────────────────────────────────────
DATA_ENCRYPTION_KEY = os.getenv('DATA_ENCRYPTION_KEY', '')
