# Generated by Django 6.0.2 on 2026-03-17 18:10

import django.db.models.deletion
import django.utils.timezone
import published_student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iinstitutes_list', '0005_remove_schedules_and_unique_ids_artifacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_student_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(db_index=True, default='', max_length=100)),
                ('access_key', models.CharField(db_index=True, default=published_student.models.generate_published_key, max_length=15)),
                ('student_data', models.JSONField(default=dict)),
                ('subjects_assigned', models.JSONField(default=list)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_students', to='iinstitutes_list.institute')),
            ],
            options={
                'indexes': [models.Index(fields=['institute', 'source_student_id'], name='pub_student_lookup_idx'), models.Index(fields=['institute', 'name'], name='pub_student_name_idx'), models.Index(fields=['institute', 'access_key'], name='pub_student_key_idx')],
                'constraints': [models.UniqueConstraint(fields=('institute', 'source_student_id'), name='uniq_published_student_institute_source')],
            },
        ),
    ]
