# Generated by Django 6.0.2 on 2026-03-17 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0005_remove_schedules_and_unique_ids_artifacts'),
        ('published_student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='publishedstudent',
            name='pub_student_key_idx',
        ),
        migrations.AddField(
            model_name='publishedstudent',
            name='student_personal_id',
            field=models.CharField(db_index=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='publishedstudent',
            index=models.Index(fields=['institute', 'student_personal_id'], name='pub_student_pid_idx'),
        ),
        migrations.RemoveField(
            model_name='publishedstudent',
            name='access_key',
        ),
    ]
