# Generated by Django 6.0.2 on 2026-03-17 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iinstitutes_list', '0004_remove_institute_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_exam_schedule_dates', to='iinstitutes_list.institute')),
            ],
        ),
        migrations.CreateModel(
            name='ExamScheduleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=50)),
                ('branch', models.CharField(default='', max_length=100)),
                ('academic_term', models.CharField(default='', max_length=50)),
                ('start_time', models.TimeField(default='')),
                ('end_time', models.TimeField(default='')),
                ('subject', models.CharField(default='', max_length=30)),
                ('room_number', models.CharField(default='', max_length=10)),
                ('type', models.CharField(default='', max_length=15)),
                ('exam_schedule_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedule_data', to='weekly_exam_schedule.examscheduledate')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=15)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_exam_schedule_days', to='iinstitutes_list.institute')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyScheduleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=50)),
                ('branch', models.CharField(default='', max_length=100)),
                ('academic_term', models.CharField(default='', max_length=50)),
                ('start_time', models.TimeField(default='')),
                ('end_time', models.TimeField(default='')),
                ('subject', models.CharField(default='', max_length=30)),
                ('room_number', models.CharField(default='', max_length=10)),
                ('professor', models.CharField(default='', max_length=30)),
                ('weekly_schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule_data', to='weekly_exam_schedule.weeklyscheduleday')),
            ],
        ),
    ]
