# Generated by Django 6.0.2 on 2026-03-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weekly_exam_schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examscheduledata',
            index=models.Index(fields=['class_name', 'branch', 'academic_term', 'exam_schedule_date'], name='exam_sched_hierarchy_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyscheduledata',
            index=models.Index(fields=['class_name', 'branch', 'academic_term', 'weekly_schedule_day'], name='weekly_sched_hierarchy_idx'),
        ),
    ]
