# Generated by Django 6.0.2 on 2026-03-17 12:39

import django.db.models.deletion
from django.db import migrations, models


def backfill_institute(apps, schema_editor):
    """Populate institute from parent on existing child rows."""
    WeeklyScheduleData = apps.get_model('weekly_exam_schedule', 'WeeklyScheduleData')
    ExamScheduleData = apps.get_model('weekly_exam_schedule', 'ExamScheduleData')

    # Backfill weekly schedule data
    rows = (
        WeeklyScheduleData.objects
        .select_related('weekly_schedule_day')
        .filter(institute__isnull=True)
    )
    to_update = []
    for row in rows:
        row.institute_id = row.weekly_schedule_day.institute_id
        to_update.append(row)
    WeeklyScheduleData.objects.bulk_update(to_update, ['institute_id'])

    # Backfill exam schedule data
    rows = (
        ExamScheduleData.objects
        .select_related('exam_schedule_date')
        .filter(institute__isnull=True)
    )
    to_update = []
    for row in rows:
        row.institute_id = row.exam_schedule_date.institute_id
        to_update.append(row)
    ExamScheduleData.objects.bulk_update(to_update, ['institute_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0004_remove_institute_status_and_more'),
        ('weekly_exam_schedule', '0002_examscheduledata_exam_sched_hierarchy_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examscheduledata',
            name='exam_sched_hierarchy_idx',
        ),
        migrations.RemoveIndex(
            model_name='weeklyscheduledata',
            name='weekly_sched_hierarchy_idx',
        ),
        migrations.AddField(
            model_name='examscheduledata',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedule_data', to='iinstitutes_list.institute'),
        ),
        migrations.AddField(
            model_name='weeklyscheduledata',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule_data', to='iinstitutes_list.institute'),
        ),
        migrations.RunPython(backfill_institute, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='examscheduledata',
            index=models.Index(fields=['institute', 'class_name', 'branch', 'academic_term', 'exam_schedule_date'], name='esd_inst_hierarchy_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyscheduledata',
            index=models.Index(fields=['institute', 'class_name', 'branch', 'academic_term', 'weekly_schedule_day'], name='wsd_inst_hierarchy_idx'),
        ),
    ]
