# Generated by Django 6.0.2 on 2026-02-23 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('father_name', models.CharField(default='', max_length=100)),
                ('mother_name', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.DateField(default='')),
                ('gender', models.CharField(default='', max_length=100)),
                ('phone_number', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('indentity_number', models.CharField(default='', max_length=100)),
                ('marital_status', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_address', models.CharField(default='', max_length=100)),
                ('permanent_address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='professors.professor')),
            ],
        ),
        migrations.CreateModel(
            name='professorAdminEmployement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_id', models.CharField(default='', max_length=100)),
                ('date_of_joining', models.DateField(default='')),
                ('employement_type', models.CharField(default='', max_length=100)),
                ('working_hours', models.CharField(default='', max_length=100)),
                ('salary', models.CharField(default='', max_length=100)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_employement', to='professors.professor')),
            ],
        ),
        migrations.CreateModel(
            name='professorClassAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_course', models.CharField(default='', max_length=100)),
                ('assigned_section', models.CharField(default='', max_length=100)),
                ('assigned_year', models.CharField(default='', max_length=100)),
                ('session', models.CharField(default='', max_length=100)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='class_assigned', to='professors.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(default='', max_length=100)),
                ('department', models.CharField(default='', max_length=100)),
                ('teaching_subject', models.CharField(default='', max_length=100)),
                ('teaching_experience', models.CharField(default='', max_length=100)),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='professors.professor')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='', max_length=100)),
                ('institution', models.CharField(default='', max_length=100)),
                ('year_of_passing', models.CharField(default='', max_length=100)),
                ('percentage', models.CharField(default='', max_length=100)),
                ('specialization', models.CharField(default='', max_length=100)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='professors.professor')),
            ],
        ),
    ]
