# Generated by Django 6.0.2 on 2026-02-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professoradminemployement',
            name='employee_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
