# Generated by Django 6.0.2 on 2026-02-27 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0001_initial'),
        ('professors', '0002_professoradminemployement_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='iinstitutes_list.institute'),
        ),
    ]
