# Generated by Django 6.0.2 on 2026-02-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0003_professor_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
