# Generated by Django 6.0.2 on 2026-02-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0004_professor_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorexperience',
            name='interest',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='professor',
            name='father_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professor',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='professor',
            name='indentity_number',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professor',
            name='marital_status',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='professor',
            name='mother_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professor',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professor',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='professoraddress',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='professoraddress',
            name='country',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='professoraddress',
            name='state',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='professoradminemployement',
            name='employee_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professoradminemployement',
            name='employement_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='professoradminemployement',
            name='personal_id',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professoradminemployement',
            name='salary',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='professoradminemployement',
            name='working_hours',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='professorclassassigned',
            name='assigned_course',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professorclassassigned',
            name='assigned_section',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='professorclassassigned',
            name='assigned_year',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='professorclassassigned',
            name='session',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='professorexperience',
            name='department',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professorexperience',
            name='designation',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professorexperience',
            name='teaching_experience',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='professorexperience',
            name='teaching_subject',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professorqualification',
            name='degree',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='professorqualification',
            name='institution',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professorqualification',
            name='percentage',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='professorqualification',
            name='specialization',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='professorqualification',
            name='year_of_passing',
            field=models.CharField(default='', max_length=10),
        ),
    ]
