# Generated by Django 6.0.2 on 2026-03-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0005_professorexperience_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professoradminemployement',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
