# Generated by Django 6.0.2 on 2026-03-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0005_remove_schedules_and_unique_ids_artifacts'),
        ('professors', '0006_alter_professor_age_alter_professor_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['institute', 'email'], name='prof_inst_email_idx'),
        ),
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['institute', 'phone_number'], name='prof_inst_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='professoradminemployement',
            index=models.Index(fields=['personal_id'], name='prof_admin_pid_idx'),
        ),
    ]
