# Generated by Django 6.0.2 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professors', '0007_professor_prof_inst_email_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='professor',
            index=models.Index(fields=['institute', 'name'], name='prof_inst_name_idx'),
        ),
        migrations.AddIndex(
            model_name='professoradminemployement',
            index=models.Index(fields=['employee_id'], name='prof_admin_empid_idx'),
        ),
        migrations.AddIndex(
            model_name='professorexperience',
            index=models.Index(fields=['department'], name='prof_exp_dept_idx'),
        ),
    ]
