# Generated by Django 6.0.2 on 2026-03-29 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iinstitutes_list', '0006_institute_institute_name_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubordinateAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('access_control', models.CharField(default='', max_length=100)),
                ('access_code', models.CharField(default='', max_length=39)),
                ('is_varified', models.BooleanField(default=False)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_accesses', to='iinstitutes_list.institute')),
            ],
            options={},
        ),
        migrations.AddIndex(
            model_name='subordinateaccess',
            index=models.Index(fields=['institute'], name='subacc_institute_idx'),
        ),
        migrations.AddIndex(
            model_name='subordinateaccess',
            index=models.Index(fields=['institute', 'name'], name='subacc_inst_name_idx'),
        ),
        migrations.AddIndex(
            model_name='subordinateaccess',
            index=models.Index(fields=['institute', 'access_code'], name='subacc_inst_code_idx'),
        ),
    ]
