# Generated by Django 6.0.2 on 2026-03-29 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0006_institute_institute_name_idx'),
        ('subordinate_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubordinateAccessVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinate_access_verification_requests', to='iinstitutes_list.institute')),
                ('subordinate_access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='subordinate_access.subordinateaccess')),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='subordinateaccessverificationrequest',
            index=models.Index(fields=['status', 'requested_at'], name='subacc_req_status_idx'),
        ),
        migrations.AddIndex(
            model_name='subordinateaccessverificationrequest',
            index=models.Index(fields=['institute', 'status'], name='subacc_req_inst_status_idx'),
        ),
    ]
