# Generated by Django 6.0.2 on 2026-02-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0005_subject_delete_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='unit',
            field=models.IntegerField(default=0),
        ),
    ]
