# Generated by Django 6.0.2 on 2026-02-27 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0001_initial'),
        ('syllabus', '0006_subject_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='iinstitutes_list.institute'),
        ),
    ]
