# Generated by Django 6.0.2 on 2026-03-13 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0008_remove_subject_course_branch_subject_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_terms', to='syllabus.branch')),
            ],
        ),
    ]
