# Generated by Django 6.0.2 on 2026-03-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syllabus', '0009_academicterms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='branch',
        ),
        migrations.AddField(
            model_name='subject',
            name='academic_terms',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='syllabus.academicterms'),
            preserve_default=False,
        ),
    ]
