# Generated by Django 6.0.2 on 2026-03-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0006_institute_institute_name_idx'),
        ('syllabus', '0010_remove_subject_branch_subject_academic_terms'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='academicterms',
            index=models.Index(fields=['branch'], name='acterm_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['course'], name='branch_course_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['institute'], name='course_institute_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['academic_terms'], name='subject_acterm_idx'),
        ),
    ]
