# Generated by Django 6.0.2 on 2026-03-11 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mClass', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'exam_class',
            },
        ),
        migrations.CreateModel(
            name='ExamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssubject', models.CharField(default='', max_length=40)),
                ('exam_type', models.CharField(default='', max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('exam_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_data', to='set_exam_data.examclass')),
            ],
            options={
                'db_table': 'exam_data',
            },
        ),
    ]
