# Generated by Django 6.0.2 on 2026-03-11 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0004_remove_institute_status_and_more'),
        ('set_exam_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examclass',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exam_classes', to='iinstitutes_list.institute'),
            preserve_default=False,
        ),
    ]
