# Generated by Django 6.0.2 on 2026-03-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_exam_data', '0002_examclass_institute'),
        ('students', '0015_subjectsassigned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObtainedMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.IntegerField(default=0)),
                ('exam_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obtained_marks', to='set_exam_data.examdata')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obtained_marks', to='students.student')),
            ],
            options={
                'db_table': 'obtained_marks',
            },
        ),
    ]
