# Generated by Django 6.0.2 on 2026-03-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_exam_data', '0003_obtainedmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examdata',
            name='ssubject',
        ),
        migrations.AddField(
            model_name='examdata',
            name='subject',
            field=models.CharField(default='', max_length=40),
        ),
    ]
