# Generated by Django 6.0.2 on 2026-03-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_exam_data', '0004_remove_examdata_ssubject_examdata_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='examclass',
            name='branch',
            field=models.CharField(default='', max_length=40),
        ),
    ]
