# Generated by Django 6.0.2 on 2026-03-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('set_exam_data', '0006_restructure_exam_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exambranch',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
    ]
