# Generated by Django 6.0.2 on 2026-03-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0004_remove_institute_status_and_more'),
        ('set_exam_data', '0007_alter_exambranch_branch'),
        ('students', '0017_add_subjects_assigned_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='examacedemicterm',
            index=models.Index(fields=['exam_branch', 'academic_term'], name='examterm_branch_term_idx'),
        ),
        migrations.AddIndex(
            model_name='exambranch',
            index=models.Index(fields=['exam_class', 'branch'], name='exambranch_class_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='examclass',
            index=models.Index(fields=['institute', 'mClass'], name='examclass_inst_class_idx'),
        ),
        migrations.AddIndex(
            model_name='examdata',
            index=models.Index(fields=['exam_academic_term', 'subject'], name='examdata_term_subj_idx'),
        ),
        migrations.AddIndex(
            model_name='examdata',
            index=models.Index(fields=['exam_academic_term', 'exam_type'], name='examdata_term_type_idx'),
        ),
        migrations.AddIndex(
            model_name='obtainedmarks',
            index=models.Index(fields=['exam_data', 'student'], name='obtmarks_examdata_student_idx'),
        ),
        migrations.AddIndex(
            model_name='obtainedmarks',
            index=models.Index(fields=['student'], name='obtmarks_student_idx'),
        ),
    ]
