# Generated by Django 6.0.2 on 2026-03-17 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0004_remove_institute_status_and_more'),
        ('set_exam_data', '0008_add_exam_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examacedemicterm',
            name='examterm_branch_term_idx',
        ),
        migrations.RemoveIndex(
            model_name='exambranch',
            name='exambranch_class_branch_idx',
        ),
        migrations.RemoveIndex(
            model_name='examclass',
            name='examclass_inst_class_idx',
        ),
        migrations.RemoveIndex(
            model_name='examdata',
            name='examdata_term_subj_idx',
        ),
        migrations.RemoveIndex(
            model_name='examdata',
            name='examdata_term_type_idx',
        ),
        migrations.AddField(
            model_name='examdata',
            name='academic_term',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='examdata',
            name='branch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='examdata',
            name='class_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='examdata',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_data_flat', to='iinstitutes_list.institute'),
        ),
        migrations.AddIndex(
            model_name='examdata',
            index=models.Index(fields=['institute', 'class_name', 'branch', 'academic_term'], name='examdata_inst_hierarchy_idx'),
        ),
        migrations.AddIndex(
            model_name='examdata',
            index=models.Index(fields=['institute', 'class_name', 'branch', 'academic_term', 'subject'], name='examdata_inst_subj_idx'),
        ),
        migrations.AlterModelTable(
            name='examdata',
            table=None,
        ),
        migrations.RemoveField(
            model_name='examacedemicterm',
            name='exam_branch',
        ),
        migrations.RemoveField(
            model_name='examclass',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='examdata',
            name='exam_academic_term',
        ),
        migrations.DeleteModel(
            name='ExamBranch',
        ),
        migrations.DeleteModel(
            name='ExamClass',
        ),
        migrations.DeleteModel(
            name='ExamAcedemicTerm',
        ),
    ]
