# Generated by Django 6.0.2 on 2026-02-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='')),
                ('end_time', models.TimeField(default='')),
                ('subject', models.CharField(default='', max_length=30)),
                ('classes', models.CharField(default='', max_length=20)),
                ('room_number', models.CharField(default='', max_length=10)),
                ('exam_date', models.DateField(default='')),
                ('type', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='')),
                ('end_time', models.TimeField(default='')),
                ('day', models.CharField(default='', max_length=15)),
                ('subject', models.CharField(default='', max_length=30)),
                ('classes', models.CharField(default='', max_length=20)),
                ('room_number', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
