# Generated by Django 6.0.2 on 2026-02-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='professor',
            field=models.CharField(default='', max_length=30),
        ),
    ]
