# Generated by Django 6.0.2 on 2026-02-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_weeklyschedule_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyScheduleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='')),
                ('end_time', models.TimeField(default='')),
                ('subject', models.CharField(default='', max_length=30)),
                ('classes', models.CharField(default='', max_length=20)),
                ('room_number', models.CharField(default='', max_length=10)),
                ('professor', models.CharField(default='', max_length=30)),
                ('weekly_schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule_data', to='schedules.weeklyscheduleday')),
            ],
        ),
    ]
