# Generated by Django 6.0.2 on 2026-02-25 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_weeklyscheduleday_weeklyscheduledata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheduleDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamScheduleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default='')),
                ('end_time', models.TimeField(default='')),
                ('subject', models.CharField(default='', max_length=30)),
                ('classes', models.CharField(default='', max_length=20)),
                ('room_number', models.CharField(default='', max_length=10)),
                ('type', models.CharField(default='', max_length=15)),
                ('exam_schedule_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedule_data', to='schedules.examscheduledate')),
            ],
        ),
    ]
