# Generated by Django 6.0.2 on 2026-02-27 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0001_initial'),
        ('schedules', '0004_examscheduledate_examscheduledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='examscheduledate',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedule_dates', to='iinstitutes_list.institute'),
        ),
        migrations.AddField(
            model_name='weeklyscheduleday',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedule_days', to='iinstitutes_list.institute'),
        ),
    ]
