# Generated by Django 6.0.2 on 2026-03-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iinstitutes_list', '0005_remove_schedules_and_unique_ids_artifacts'),
        ('published_professors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('total_days', models.PositiveIntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_leaves', to='iinstitutes_list.institute')),
                ('published_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='published_professors.publishedprofessor')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['institute', 'start_date'], name='prof_leave_inst_start_idx'),
                    models.Index(fields=['institute', 'published_professor'], name='prof_leave_inst_prof_idx'),
                ],
                'constraints': [
                    models.UniqueConstraint(fields=('published_professor', 'start_date', 'end_date'), name='uniq_prof_leave_prof_date_range'),
                ],
            },
        ),
    ]
