# Generated by Django 6.0.2 on 2026-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorleave',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='professorleave',
            name='leaves_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending'),
                    ('accepted', 'Accepted'),
                    ('cancelled', 'Cancelled'),
                ],
                default='pending',
                max_length=10,
            ),
        ),
    ]
