# Generated by Django 6.0.2 on 2026-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_leaves', '0002_professorleave_leaves_status_and_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorleave',
            name='total_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
