# Generated by Django 6.0.2 on 2026-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_leaves', '0003_professorleave_total_leaves'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorleave',
            name='remaining_leaves',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
