# Generated by Django 6.0.2 on 2026-03-25 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0006_institute_institute_name_idx'),
        ('professor_leaves', '0004_professorleave_remaining_leaves'),
        ('published_professors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorleave',
            name='remaining_leaves',
        ),
        migrations.RemoveField(
            model_name='professorleave',
            name='total_leaves',
        ),
        migrations.CreateModel(
            name='ProfessorTotalLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor_name', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('total_leaves', models.PositiveIntegerField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professor_total_leaves', to='iinstitutes_list.institute')),
                ('published_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_leave_records', to='published_professors.publishedprofessor')),
            ],
            options={
                'indexes': [models.Index(fields=['institute', 'published_professor'], name='prof_total_leave_inst_prof_idx')],
                'constraints': [models.UniqueConstraint(fields=('published_professor',), name='uniq_prof_total_leave_professor')],
            },
        ),
    ]
