# Generated by Django 6.0.2 on 2026-03-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_leaves', '0005_remove_professorleave_remaining_leaves_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='professortotalleave',
            name='prof_total_leave_inst_prof_idx',
        ),
        migrations.RemoveConstraint(
            model_name='professortotalleave',
            name='uniq_prof_total_leave_professor',
        ),
        migrations.DeleteModel(
            name='ProfessorTotalLeave',
        ),
    ]
