# Generated by Django 6.0.2 on 2026-03-25 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iinstitutes_list', '0006_institute_institute_name_idx'),
        ('professor_leaves', '0006_remove_professortotalleave_prof_total_leave_inst_prof_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteTotalLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leaves', models.PositiveIntegerField(default=0)),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor_total_leave_setting', to='iinstitutes_list.institute')),
            ],
        ),
    ]
