# Generated by Django 6.0.2 on 2026-03-28 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iinstitutes_list', '0006_institute_institute_name_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('academic_term', models.CharField(max_length=50)),
                ('schedule_data', models.JSONField(default=list)),
                ('source_hash', models.CharField(default='', max_length=64)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_exam_schedules', to='iinstitutes_list.institute')),
            ],
            options={
                'indexes': [models.Index(fields=['institute', 'class_name', 'branch', 'academic_term'], name='pub_exam_hierarchy_idx')],
                'constraints': [models.UniqueConstraint(fields=('institute', 'class_name', 'branch', 'academic_term'), name='uniq_pub_exam_schedule')],
            },
        ),
        migrations.CreateModel(
            name='PublishedWeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=100)),
                ('academic_term', models.CharField(max_length=50)),
                ('schedule_data', models.JSONField(default=list)),
                ('source_hash', models.CharField(default='', max_length=64)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_weekly_schedules', to='iinstitutes_list.institute')),
            ],
            options={
                'indexes': [models.Index(fields=['institute', 'class_name', 'branch', 'academic_term'], name='pub_weekly_hierarchy_idx')],
                'constraints': [models.UniqueConstraint(fields=('institute', 'class_name', 'branch', 'academic_term'), name='uniq_pub_weekly_schedule')],
            },
        ),
    ]
