# Generated by Django 6.0.2 on 2026-03-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branch',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='year_semester',
            field=models.CharField(default='', max_length=20),
        ),
    ]
