# Generated by Django 6.0.2 on 2026-03-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_branch_attendance_class_name_and_more'),
        ('professors', '0006_alter_professor_age_alter_professor_date_of_birth_and_more'),
        ('students', '0016_sync_student_schema_with_models'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='att_student_date_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['class_name', 'branch', 'date'], name='att_class_branch_date_idx'),
        ),
    ]
